Fix non-standard DFLOAT intrinsic in WRF physics module_mp_thompson.F
module_mp_thompson.F:3844:22:

 3844 |          Texp = DEXP( DFLOAT(k) - T_adjust*1.0D0 ) - 1.0D0
      |                      1
Error: Function ‘dfloat’ at (1) has no IMPLICIT type

The NAG 7.0 compiler produces the following errors:

Error: module_mp_thompson.F, line 662: KIND value (8) does not specify a valid representation method
Error: module_mp_thompson.F, line 674: KIND value (8) does not specify a valid representation method
Error: module_mp_thompson.F, line 686: KIND value (8) does not specify a valid representation method
Error: module_mp_thompson.F, line 698: KIND value (8) does not specify a valid representation method
Error: module_mp_thompson.F, line 710: KIND value (8) does not specify a valid representation method
Error: module_mp_thompson.F, line 3844: KIND value (8) does not specify a valid representation method

Use KIND=R8SIZE rather than KIND=8, since module_mp_thompson already defines R8SIZE.