Fix non-standard declarations of 8-byte integers in ESMF_BaseMod.F90
ESMF_BaseMod.F90:75:20:

   75 |           integer*8 :: ptr
      |                    1
Error: GNU Extension: Nonstandard type declaration INTEGER*8 at (1)

Fix compilation errors with NAG 7.0:

Error: ESMF_BaseMod.F90, line 75: KIND value (8) does not specify a valid representation method
Error: ESMF_BaseMod.F90, line 163: KIND value (8) does not specify a valid representation method

Since the ESMF_BaseMod module already defined ESMF_KIND_I8, use

   integer(kind=ESMF_KIND_I8)

rather than

   integer(kind=8)